[api]
dashboard = true
insecure = true

[entryPoints]
[entryPoints.web]
address = ":80"
[entryPoints.websecure]
address = ":443"

[providers]
[providers.docker]
watch = true
exposedByDefault = false
network = "web"
